name: Run Test Node

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: test-node
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      USERNAME: "Github-Dev-Node"
      BRANCH: "dev"
      REQUIRE_DHT_READY: "false"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Start node
        run: timeout 21000 bun start